export const caseStudies = [
    {
      service: 'ZoZoho Creatorho Creator',
      industry: 'Finance',
      geo: 'North America',
      heading:'Zoho Creator : Grant Life Cycle Tracking Application',
      title: 'Grant Management Streamlined, Enhancing Efficiency, Transparency, and Collaboration',
      subtitle: 'The application designed by Helios Tech Labs’ Zoho Creator team enabled the client to streamline processes with customized dashboards, real-time tracking and advanced supervision.',
      image: 'https://loannow.in/case/creator.jpg',
      videoId: "Tfr2jvYrlMY", 
    },
    {
      service: 'Zoho Books',
      industry: 'Healthcare',
      geo: 'Europe',
      heading:'Zoho Books: Introducing Fixed Assets Register',
      title: 'Zoho Books accelerated with Fixed Assets Register',
      subtitle: 'Discover how Helios Tech Labs improved Zoho Books by building a Fixed Assets Register, cutting-edge technology that has helped many businesses and Zoho Partners.',
      image: 'https://loannow.in/case/books1.jpg',
      videoId: "pqig4KekweY", 
    },
    {
      service: 'Zoho Creator',
      industry: 'Retail',
      geo: 'Asia',
      heading:'Zoho Creator : Shipment Status and Information Tracking',
      title: 'Transforming Global Trading with Zoho Creator',
      subtitle: 'By leveraging the power of Zoho Creator, Helios Tech Labs was able to revolutionize the way traders accessed information. Find out how we used this to enhance their shipment tracking outcomes.',
      image: 'https://loannow.in/case/Books2.jpg',
      videoId: "ge9lWaejICo", 
    },
    {
      service: 'Zoho Creator',
      industry: 'Healthcare',
      geo: 'South America',
      heading:'Zoho Creator : Queue Management System',
      title: 'Supercharging Efficiency for a Leading Healthcare Company',
      subtitle: 'Helios Tech Labs boosts efficiency and effectiveness for a top hospital, modernizing tech for an enhanced patient experience.',
      image: 'https://loannow.in/case/creator3.jpg',
      videoId: "EqC90e3yvw8", 
    },
    {
      service: 'Zoho Creator',
      industry: 'Food & Beverage',
      geo: 'North America',
      heading:'Zoho Creator : Field Support System for a large beverage company',
      title: 'Distributor Gains Efficiency with Field Support System',
      subtitle: 'Using Zoho Creator, Helios Tech Labs helped a beverage distributor company with increased productivity and revenue.',
      image: 'https://loannow.in/case/creator4.jpg',
      videoId: "FJEaF-29Gno", 
    },
    {
      service: 'Zoho Creator',
      industry: 'Facilities Management',
      geo: 'Europe',
      heading:'Zoho Creator: Panoramic Facilities Management Application',
      title: 'Digital Transformation at Facilities Management Company',
      subtitle: 'Find out how Helios Tech Labs developed Zoho Creator to provide a centralized database with accurate information whenever needed.',
      image: 'https://loannow.in/case/creator5.jpg', 
      videoId: "Er3nUeWDMGU",
    },
    {
      service: 'Zoho Books',
      industry: 'Retail',
      geo: 'Asia',
      heading:'Zoho Books: Introducing Multi Invoice Credit Note',
      title: 'Enhancing Operations with Multi Invoice Credit Notes on Zoho Books',
      subtitle: 'See how Helios Tech Labs is improving operations efficiency and driving many invoices in real-time.',
      image: 'https://loannow.in/case/Books3.jpg',
      videoId: "lsDzTotaAo8",
    },
    {
      service: 'Zoho CRM',
      industry: 'Finance',
      geo: 'North America',
      heading:'Zoho CRM : CRM Automation for a large fin-tech company ',
      title: 'Unifying CRM Operations for a Large Fin-Tech Player',
      subtitle: 'This CRM transformation enhances dealing services for a banking giant, reducing costs significantly and boosting operations.',
      image: 'https://loannow.in/case/crm1.jpg', 
      videoId: "kU_-UZsjfE0",
    },
    {
      service: 'Zoho CRM',
      industry: 'Retail',
      geo: 'Europe',
      heading:'Zoho CRM : Automation of Sales Incentive',
      title: 'Introducing Automation of Incentivization on Zoho CRM',
      subtitle: 'Helios Tech Labs streamlined management of incentives in Zoho CRM on the basis of quantity and value.',
      image: 'https://loannow.in/case/crm2.jpg', 
      videoId: "XgaoTx1558g",
    },
    {
      service: 'Zoho Desk',
      industry: 'Education',
      geo: 'South America',
      heading:'Zoho Desk : Complete Support Solution for educational institution',
      title: 'Customer Service Transformation for Educational Institution',
      subtitle: 'Helios Tech Labs used Zoho Desk platform to help an educational institution reduce time-consuming service tasks.',
      image: 'https://loannow.in/case/desk1.jpg',
      videoId: "P-rRLk7PLkY", 
    },
    {
      service: 'Zoho Creator',
      industry: 'Payroll',
      geo: 'Africa',
      heading:'Zoho Creator : Complete Payroll application on Zoho Creator',
      title: 'Breaking Zoho Payroll Barriers: A Zoho Creator Journey',
      subtitle: 'Entrusted with digital transformations for over 10 years, Helios Tech Labs enabled a dynamic payroll system for regions where Zoho Payroll is still unavailable.',
      image: 'https://loannow.in/case/payroll1.png', 
      videoId: "ge9lWaejICo",
    },
    {
      service: 'Zoho Recruit',
      industry: 'Advisory',
      geo: 'Asia',
      heading:'Zoho Recruit : Seamless recruitment solution for a large advisory group',
      title: 'Seamless Recruitment Solution for a Large Advisory Group',
      subtitle: 'We delivered cost savings, performance improvement, and a future-proof human resource infrastructure for a leading Asian advisory group specializing in taxation and CFO solutions.',
      image: 'https://loannow.in/case/recruit1.png',
      videoId: "wB8jXuDuPRE", 
    },
    {
      service: 'Zoho Projects',
      industry: 'Project Management',
      geo: 'North America',
      heading:'Zoho Projects : Introducing Restrictive filters and integrated reports',
      title: 'Unveiling Restrictive Filters and Integrated Reports on Zoho Projects',
      subtitle: 'Helios Tech Labs fortified some groundbreaking features on Zoho Projects, custom filters and integrated reports developed to display entire consolidated data.',
      image: 'https://loannow.in/case/projects1.png', 
      videoId: "0OYzdy-Zkng",
    },
    {
      service: 'Zoho Projects',
      industry: 'Project Management',
      geo: 'North America',
      heading:'Zoho Projects : Introducing Restrictive filters and integrated reports',
      title: 'Unveiling Restrictive Filters and Integrated Reports on Zoho Projects',
      subtitle: 'Helios Tech Labs fortified some groundbreaking features on Zoho Projects, custom filters and integrated reports developed to display entire consolidated data.',
      image: 'https://loannow.in/case/projects1.png', 
      videoId: "wB8jXuDuPRE",
    },
    {
      service: 'Zoho Projects',
      industry: 'Project Management',
      geo: 'North America',
      heading:'Zoho Projects : Introducing Restrictive filters and integrated reports',
      title: 'Unveiling Restrictive Filters and Integrated Reports on Zoho Projects',
      subtitle: 'Helios Tech Labs fortified some groundbreaking features on Zoho Projects, custom filters and integrated reports developed to display entire consolidated data.',
      image: 'https://loannow.in/case/projects1.png',
      videoId: "wB8jXuDuPRE", 
    },
    {
      service: 'Zoho Projects',
      industry: 'Project Management',
      geo: 'North America',
      heading:'Zoho Projects : Introducing Restrictive filters and integrated reports',
      title: 'Unveiling Restrictive Filters and Integrated Reports on Zoho Projects',
      subtitle: 'Helios Tech Labs fortified some groundbreaking features on Zoho Projects, custom filters and integrated reports developed to display entire consolidated data.',
      image: 'https://loannow.in/case/projects1.png', 
      videoId: "wB8jXuDuPRE",
    },
    {
      service: 'Zoho Projects',
      industry: 'Project Management',
      geo: 'North America',
      heading:'Zoho Projects : Introducing Restrictive filters and integrated reports',
      title: 'Unveiling Restrictive Filters and Integrated Reports on Zoho Projects',
      subtitle: 'Helios Tech Labs fortified some groundbreaking features on Zoho Projects, custom filters and integrated reports developed to display entire consolidated data.',
      image: 'https://loannow.in/case/projects1.png', 
      videoId: "wB8jXuDuPRE",
    },
    {
      service: 'Zoho Projects',
      industry: 'Project Management',
      geo: 'North America',
      heading:'Zoho Projects : Introducing Restrictive filters and integrated reports',
      title: 'Unveiling Restrictive Filters and Integrated Reports on Zoho Projects',
      subtitle: 'Helios Tech Labs fortified some groundbreaking features on Zoho Projects, custom filters and integrated reports developed to display entire consolidated data.',
      image: 'https://loannow.in/case/projects1.png', 
      videoId: "wB8jXuDuPRE",
    },
    {
      service: 'Zoho Projects',
      industry: 'Project Management',
      geo: 'North America',
      heading:'Zoho Projects : Introducing Restrictive filters and integrated reports',
      title: 'Unveiling Restrictive Filters and Integrated Reports on Zoho Projects',
      subtitle: 'Helios Tech Labs fortified some groundbreaking features on Zoho Projects, custom filters and integrated reports developed to display entire consolidated data.',
      image: 'https://loannow.in/case/projects1.png', 
      videoId: "wB8jXuDuPRE",
    },
    
  ];
  